<link rel="shortcut icon" href="/-ui/assets/favicon/autobiz.ico"/>
<link href="/-ui/css/style.css?$!{TODAY.DateStr}" rel="stylesheet">
<link href="/-ui/-dl/unpkg.com/@coreui/icons@2.0.0-beta.3/css/free.min.css" rel="stylesheet">
<link href="/-ui/vendors/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet">
<link href="/-ui/vendors/chosen/chosen.css" rel="stylesheet">
<link href="/-ui/-dl/cdn.datatables.net/fixedheader/3.1.7/css/fixedHeader.dataTables.min.css" rel="stylesheet">
<link rel="stylesheet" href="/-ui/-dl/unpkg.com/scroll-hint@latest/css/scroll-hint.css">
